#pragma once

// Dumped with <3 by android1337
// Version: ++Fortnite+Release-31.10-CL-35815136
// Package: ModularGameplay
// Current Base: 0x7FF745A60000, UFunctions offsets will be relative to this base address

namespace SDK
{

	// Enum /Script/ModularGameplay.EGameFrameworkAddComponentFlags
	enum EGameFrameworkAddComponentFlags
	{
		EGameFrameworkAddComponentFlags__None = 0,
		EGameFrameworkAddComponentFlags__AddUnique = 1,
		EGameFrameworkAddComponentFlags__AddIfNotChild = 2,
		EGameFrameworkAddComponentFlags__UseAutoGeneratedName = 4,
	};

}
